name: phonebook
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  google_fonts: ^4.0.3
  image_picker: ^1.0.2
  provider: ^6.1.2
  cached_network_image: ^3.2.3
  flutter_image_compress: ^2.2.0
  path_provider: ^2.1.0
  flutter_native_splash: ^2.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/
  - assets/images/

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "assets/images/logo-bg.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  image_ios: assets/images/logo.png
  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image: assets/images/logo.png